name: Sync 

on:
  push:
    branches:
      - main

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout GitHub repo
        uses: actions/checkout@v4
        with:
          fetch-depth: 1

      - name: identity
        run: |
          git config user.name "paulin"
          git config user.email "paulin.duerwald@METAPOTT.com"

      - name: Push snapshot to Customer GitLab (develop)
        env:
          GITLAB_REPO_URL: ${{ secrets.GITLAB_REPO_URL }}
          GITLAB_USERNAME: ${{ secrets.GITLAB_USERNAME }}
          GITLAB_TOKEN: ${{ secrets.GITLAB_TOKEN }}
        run: |
          git checkout --orphan snapshot-branch
          git rm -rf .
          
          # Copy current files back
          git checkout main -- .
          
          # Commit as company
          git add -A
          git commit -m "Sync from GitHub: ${GITHUB_SHA}"
          
          # Add GitLab remote
          git remote add customer "https://${GITLAB_USERNAME}:${GITLAB_TOKEN}@${GITLAB_REPO_URL#https://}"
          
          # Force overwrite GitLab branch
          git push customer snapshot-branch:develop --force
